server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
        min-response-size: 1024

    shutdown: graceful  # WebServer Graceful shutdown (https://www.baeldung.com/spring-boot-web-server-shutdown)

spring:
    aot:
        enabled: true

    application:
        name: Spring Webflux with Multi-Tenant

    profiles:
        default: "postgres"    # NOTE: R2dbc 에서는 mysql, h2 가 schema 를 지원하지 않는다. (JDBC 에서는 지원함)

    jackson:
        serialization:
            indent-output: true
    lifecycle:
        timeout-per-shutdown-phase: 10s     # Graceful Shutdown 시간

    netty:
        leak-detection: simple

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always

    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                http.server.requests: true
                resilience4j.circuitbreaker.calls: true
