spring:
    aot:
        enabled: true

    profiles:
        default: "h2" # h2 | postgres | mysql

    data:
        redis:
            host: ${testcontainers.redis.host}
            port: ${testcontainers.redis.port}
            lettuce:
                pool:
                    enabled: true
                    max-active: 64
                    max-idle: 16
                    min-idle: 2
